// src/frontend_nuxt/pages/auth/login.vue
<script setup lang="ts">
    import Api from "~/libs/apiClass";
    import {LoginRequest, type LoginRequestBody} from "~/types/api/Auth/LoginRequest";
    import type {LoginResponseBody} from "~/types/api/Auth/LoginResponse";
    import type {User} from "~/types/model/User";
    import {useUserStore} from "~/composable/useUserStore";

    const emailModel = defineModel("email")
    const passwordModel = defineModel("password")

    const runtimeConfig = useRuntimeConfig();

    const handleLogin = async () => {
        console.log(runtimeConfig.public.apiUrl)
        const api: Api = new Api()
        let body: LoginRequestBody = {
            email: emailModel.value as string,
            password: passwordModel.value as string,
        }
        const res = await api.sendPostRequest(new LoginRequest(), body)
        if (res.ok) {
            const responseBody = await res.json() as LoginResponseBody
            const u = {
                id: responseBody.id,
                name: responseBody.name,
                email: responseBody.email
            } as User
            const store = useUserStore()
            store.set(u)

            navigateTo("/")
        }
    }
</script>

<template>
    <main>
        <div class="box">
            <h1>Login</h1>
            <div>
                <form>
                    <div>
                        <label>
                            email:
                            <input type="text" name="email" v-model="emailModel" />
                        </label>
                    </div>
                    <div>
                        <label>
                            password:
                            <input type="password" name="password" v-model="passwordModel" />
                        </label>
                    </div>
                    <button type="button" class="submit" @click="handleLogin">Login</button>
                </form>
            </div>
        </div>
    </main>
</template>

<style scoped>

</style>

// src/frontend_next/app/auth/login/page.tsx
"use client"

import {useRef} from "react"
import Api from "@/libs/ApiClass"
import {LoginRequest, LoginRequestBody} from "@/types/api/Auth/LoginRequest";
import {LoginResponseBody} from "@/types/api/Auth/LoginResponse";

export default function Page() {
    console.log(process.env.NEXT_PUBLIC_API_URL)
    const emailRef = useRef<HTMLInputElement | null>(null)
    const passwordRef = useRef<HTMLInputElement | null>(null)
    const handleLogin = async () => {
        const api: Api = new Api()
        let body: LoginRequestBody = {
            email: emailRef.current?.value!,
            password: passwordRef.current?.value!,
        }
        const res = await api.sendPostRequest(new LoginRequest(), body);
        console.log(res.status)
        const responseBody = res.data as LoginResponseBody
        console.log(responseBody.id)
    }

    return (
      <main>
          <div className="box">
              <h1>Login</h1>
              <div>
                  <form>
                      <div>
                          <label>
                              email:
                              <input type="text" name="email" ref={emailRef}/>
                          </label>
                      </div>
                      <div>
                          <label>
                              password:
                              <input type="password" name="password" ref={passwordRef} />
                          </label>
                      </div>
                      <button type="button" className="submit" onClick={handleLogin}>Login</button>
                  </form>
              </div>
          </div>
      </main>
    );
}
