// src/frontend_next/components/sections/sidebarSingle.tsx
import React from 'react';

interface Menu {
    title: string,
    icon: string,
    link: string
}
interface P {
    menu: Menu
}

const SidebarSingle = (props: P) => {
    return <li className="menu-item">
        <a href={ props.menu['link'] }>
            <span className="menu-icon">
                <i className={ props.menu['icon'] }></i>
            </span>
            <span className="menu-title">{ props.menu['title'] }</span>
            <span className="menu-suffix">
            </span>
        </a>
    </li>

}

export default SidebarSingle

// src/frontend_nuxt/components/sections/sidebarSingle.vue
<script setup lang="ts">

</script>

<template>
    <li class="menu-item">
        <a v-bind:href="props.menu['link']">
            <span class="menu-icon">
                <i class="props.menu['icon']"></i>
            </span>
            <span class="menu-title">{{ props.menu['title'] }}</span>
            <span class="menu-suffix"></span>
        </a>
    </li>
</template>

<style scoped>

</style>
